/* Amazon competitor discovery and explicitly requested history snapshots. */
const watch={productId:'',busy:false};
function latestHistory(id){return [...(state.project?.watch_history||[])].reverse().find(x=>x.product_id===id)}
function watchValue(value,decimals=0){return typeof value==='number'&&Number.isFinite(value)?value.toLocaleString('zh-CN',{maximumFractionDigits:decimals}):'未提供'}
function historyResult(history,tool){return history?.results?.find(x=>x.tool===tool)}
function lastPoint(points){return [...(points||[])].reverse().find(x=>typeof x.value==='number'&&Number.isFinite(x.value))}
function priceChart(points,label='历史价格 · USD'){
 const rows=(points||[]).filter(x=>typeof x.value==='number'&&Number.isFinite(x.value)&&Number.isFinite(Date.parse(x.at)));
 if(rows.length<2)return '<p class="caption">价格时间点不足，暂不绘制趋势。</p>';
 const values=rows.map(x=>x.value),times=rows.map(x=>Date.parse(x.at)),lo=Math.min(...values),hi=Math.max(...values),start=Math.min(...times),end=Math.max(...times),span=hi-lo||1;
 const line=rows.map((x,i)=>`${i?'L':'M'}${(45+(Date.parse(x.at)-start)/(end-start||1)*670).toFixed(1)},${(145-(x.value-lo)/span*105).toFixed(1)}`).join(' ');
 return `<figure class="watch-chart"><figcaption>${esc(label)}</figcaption><svg viewBox="0 0 760 195" role="img" aria-label="${esc(label)}，供应商返回时间点"><path d="M45 20V150H715" fill="none" stroke="#dbe1e8"/><text x="5" y="40">${watchValue(hi,2)}</text><text x="5" y="150">${watchValue(lo,2)}</text><path d="${line}" fill="none" stroke="#1765d1" stroke-width="2"/><text x="45" y="177">${esc(rows[0].at.slice(0,10))}</text><text x="625" y="177">${esc(rows.at(-1).at.slice(0,10))}</text></svg><p class="caption">按返回时间点连线；不是实时价格，缺失值不补齐。</p></figure>`;
}
function historyPriceChart(points,months){
 const valid=(points||[]).filter(x=>typeof x.value==='number'&&Number.isFinite(x.value));
 if(valid.length>=2)return priceChart(points);
 const average=(months||[]).filter(x=>typeof x.average_price==='number'&&Number.isFinite(x.average_price)).map(x=>({at:x.month+'-01T00:00:00Z',value:x.average_price}));
 return average.length>=2?'<p class="caption">近 90 天价格记录不足，以下展示供应商返回的月均价格；两者统计口径不同。</p>'+priceChart(average,'月均价格 · USD'):priceChart(points);
}
function historyBody(history){
 if(!history)return '';
 const keepa=historyResult(history,'keepa_info'),sales=historyResult(history,'asin_sales_trend'),series=keepa?.data?.series||{},months=sales?.data?.months||[];
 const linkedAsins=[...new Set([keepa?.data?.data_asin,keepa?.data?.returned_asin].filter(x=>x&&x!==keepa?.data?.requested_asin))];
 const missingPoints=Object.values(series).reduce((sum,points)=>sum+points.filter(x=>x.value===null).length,0),missingSales=months.reduce((sum,x)=>sum+['parent_units','child_units','average_price'].filter(k=>x[k]===null).length,0);
 const statuses={running:'查询中',success:'已保存',partial:'部分结果已保存',failed:'查询失败'};
 return `<p class="report-meta">${esc(statuses[history.status]||history.status)} · ${date(history.finished_at||history.created_at)} · 手动查询 ${watchValue(history.requests)} / ${watchValue(history.request_limit)} 次 · ${esc(history.source)}</p>${(history.results||[]).filter(x=>x.status==='failed').map(x=>`<p class="error-inline">${x.tool==='keepa_info'?'价格与排名':'月度销量'}：${esc(x.error)}${x.http?'（HTTP '+Number(x.http)+'）':''}</p>`).join('')}${keepa?.status==='success'?`${linkedAsins.length?`<div class="source-note">供应商返回关联商品 ${linkedAsins.map(esc).join("、")}，与所选 ${esc(keepa.data.requested_asin)} 不同，不能直接作为所选商品的走势。</div>`:''}<div class="report-numbers">${[['最新记录价格',series.price,2],['BSR 排名',series.bsr,0],['评分数',series.ratings_count,0],['评分',series.rating,1]].map(([label,points,precision])=>{const x=lastPoint(points);return `<div><strong>${watchValue(x?.value,precision)}</strong><span>${label}</span><p class="caption">${x?esc(x.at.slice(0,10)):'未提供'}</p></div>`}).join('')}</div>${historyPriceChart(series.price,months)}<p class="caption">价格与排名等记录：跳过异常、重复或超出范围时间点 ${watchValue(keepa.data.skipped_points)} 个；保留缺失值时间点 ${watchValue(missingPoints)} 个，显示「未提供」，不补零。</p><details class="report-details"><summary>查看价格、排名与评分时间点</summary>${Object.entries(series).map(([name,points])=>`<h3>${esc({price:'价格（USD）',bsr:'BSR 排名',ratings_count:'评分数',rating:'评分'}[name]||name)}</h3><table><tr><th>日期</th><th>记录值</th></tr>${points.map(x=>`<tr><td>${esc(x.at.slice(0,10))}</td><td>${watchValue(x.value,2)}</td></tr>`).join('')}</table>`).join('')}</details>`:''}${sales?.status==='success'?`<h3>月度销量 · 第三方估算</h3>${sales.data.returned_asin&&sales.data.returned_asin!==sales.data.requested_asin?`<p class="source-note">销量返回商品 ${esc(sales.data.returned_asin)} 与查询商品不同，请先核对父子体关联。</p>`:''}<p class="caption">父体包含多个变体，子体对应具体商品；估算量不等于真实订单。价格为美元。销量包含供应商全部可用月份，不限于近 90 天。</p><p class="caption">销量记录：跳过异常或重复月份 ${watchValue(sales.data.skipped_points)} 个；当前表格缺失值 ${watchValue(missingSales)} 项，显示「未提供」，不补零。</p><div class="table-wrap"><table><tr><th>月份</th><th>父体月销量</th><th>子体月销量</th><th>月均价</th></tr>${months.map(x=>`<tr><td>${esc(x.month)}</td><td>${watchValue(x.parent_units)}</td><td>${watchValue(x.child_units)}</td><td>${watchValue(x.average_price,2)}</td></tr>`).join('')}</table></div>`:''}`;
}
function watchHistorySection(){const p=state.project,id=p.products.some(x=>x.id===watch.productId)?watch.productId:p.watch_history?.at(-1)?.product_id,product=p.products.find(x=>x.id===id);if(!product)return `<section class="flat-section"><h2>查看竞品变化</h2><p class="muted">先查询关键词下的商品，再点竞品的「查看趋势」。可读取历史价格、排名、评分数，以及月度销量估算。</p><p class="caption">当前按需查询，未开启定时监控。一次更新消耗 2 次 MCP 查询。</p></section>`;const history=latestHistory(id);return `<section class="report-sheet" id="watch-history"><div class="section-head"><div><h2>${esc(product.title)}</h2><p class="caption">${esc(product.asin||product.id)} · 美国站 · ${external(product.source_url,'商品页面')}</p></div>${button(watch.busy?'正在查询…':history?'更新趋势 · 2次查询':'读取历史 · 2次查询','refresh-product-history','refresh','primary',`data-id="${esc(id)}" ${watch.busy?'disabled':''}`)}</div><p class="caption">读取近 90 天的价格、BSR 与评分记录，以及供应商全部可用月份的销量估算；每次保存到当前项目，原始商品资料保留。未开启定时监控。</p>${history?historyBody(history):empty('还没有查询这件竞品的历史','点击上方读取；只调用本次所选商品的两项数据，不自动循环采集。')}</section>`}
function marketWatch(){return `<div class="watch-page">${jobView()}${products()}${watchHistorySection()}</div>`}
function watchReportHtml(){const p=state.project;const ids=[...new Set((p.watch_history||[]).map(x=>x.product_id))];return ids.length?`<h2>竞品历史观察</h2><p>按需更新，未开启定时监控；父子体销量均为供应商估算。</p>${ids.map(id=>{const product=p.products.find(x=>x.id===id);return `<h3>${esc(product?.title||id)}</h3>${historyBody(latestHistory(id))}`}).join('')}`:''}
async function watchAction(action,el){switch(action){
 case'product-history':watch.productId=el.dataset.id;if(state.page==='products')render();else goto('products');document.querySelector('#watch-history')?.scrollIntoView({behavior:'auto',block:'start'});return true;
 case'refresh-product-history':{if(watch.busy)return true;const id=state.project.id;watch.busy=true;render();try{const p=await api('/api/projects/'+id+'/product-history',{revision:state.project.revision,product_id:el.dataset.id});if(state.project?.id===id)state.project=p;const r=p.watch_history?.at(-1);toast(r?.status==='success'?'竞品历史已保存':r?.status==='partial'?'部分历史已保存，请查看失败说明':'查询未完成，请查看原因')}finally{watch.busy=false;render();if(state.project?.id===id){document.querySelector('#watch-history')?.scrollIntoView({behavior:'auto',block:'start'})}}return true}
 default:return false;
}}
